<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Subscription;
use App\Models\Booking;
use Carbon\Carbon;

class SubscriptionSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::table('subscriptions')->insert([
            [
                'id' => 1,
                'user_id' => 2,
                'membership_id' => 2,
                'trainer_id' => 9,
                'start_date' => '2026-04-06',
                'end_date' => '2026-05-06',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-11 02:18:46',
                'updated_at' => '2026-04-11 02:18:46',
            ],
            [
                'id' => 2,
                'user_id' => 3,
                'membership_id' => 5,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 900000.00,
                'pt_sessions_left' => 4,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 06:42:40',
                'updated_at' => '2026-04-13 06:42:40',
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'membership_id' => 5,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 900000.00,
                'pt_sessions_left' => 4,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 06:46:36',
                'updated_at' => '2026-04-13 06:46:36',
            ],
            [
                'id' => 4,
                'user_id' => 3,
                'membership_id' => 5,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 900000.00,
                'pt_sessions_left' => 4,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 06:47:32',
                'updated_at' => '2026-04-13 06:47:32',
            ],
            [
                'id' => 5,
                'user_id' => 3,
                'membership_id' => 5,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-06-12',
                'final_price' => 900000.00,
                'pt_sessions_left' => 3,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 06:48:51',
                'updated_at' => '2026-04-17 18:28:28',
            ],
            [
                'id' => 6,
                'user_id' => 3,
                'membership_id' => 2,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'cancelled',
                'cancel_reason' => 'ok',
                'cancelled_at' => '2026-04-22 19:52:53',
                'frozen_until' => null,
                'created_at' => '2026-04-13 07:26:57',
                'updated_at' => '2026-04-22 12:52:53',
            ],
            [
                'id' => 7,
                'user_id' => 3,
                'membership_id' => 2,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 07:27:15',
                'updated_at' => '2026-04-13 07:27:15',
            ],
            [
                'id' => 8,
                'user_id' => 3,
                'membership_id' => 2,
                'trainer_id' => null,
                'start_date' => '2026-04-13',
                'end_date' => '2026-05-13',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 07:27:55',
                'updated_at' => '2026-04-13 07:27:55',
            ],
            [
                'id' => 9,
                'user_id' => 3,
                'membership_id' => 1,
                'trainer_id' => null,
                'start_date' => '2026-04-14',
                'end_date' => '2026-05-14',
                'final_price' => 300000.00,
                'pt_sessions_left' => 0,
                'status' => 'pending_payment',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 20:05:37',
                'updated_at' => '2026-04-13 20:05:37',
            ],
            [
                'id' => 10,
                'user_id' => 3,
                'membership_id' => 1,
                'trainer_id' => null,
                'start_date' => '2026-04-14',
                'end_date' => '2026-05-14',
                'final_price' => 300000.00,
                'pt_sessions_left' => 0,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 20:08:44',
                'updated_at' => '2026-04-13 20:09:19',
            ],
            [
                'id' => 11,
                'user_id' => 3,
                'membership_id' => 1,
                'trainer_id' => null,
                'start_date' => '2026-04-14',
                'end_date' => '2026-05-14',
                'final_price' => 300000.00,
                'pt_sessions_left' => 0,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-13 20:54:42',
                'updated_at' => '2026-04-13 20:55:02',
            ],
            [
                'id' => 12,
                'user_id' => 3,
                'membership_id' => 3,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 1500000.00,
                'pt_sessions_left' => 12,
                'status' => 'cancelled',
                'cancel_reason' => 'ko',
                'cancelled_at' => '2026-04-15 08:36:15',
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:43:57',
                'updated_at' => '2026-04-14 18:36:15',
            ],
            [
                'id' => 13,
                'user_id' => 3,
                'membership_id' => 3,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 1500000.00,
                'pt_sessions_left' => 12,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:44:02',
                'updated_at' => '2026-04-14 17:45:28',
            ],
            [
                'id' => 14,
                'user_id' => 3,
                'membership_id' => 2,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:48:24',
                'updated_at' => '2026-04-14 17:48:40',
            ],
            [
                'id' => 15,
                'user_id' => 3,
                'membership_id' => 5,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 900000.00,
                'pt_sessions_left' => 4,
                'status' => 'cancelled',
                'cancel_reason' => 'ko thích tập nx',
                'cancelled_at' => '2026-04-15 08:35:49',
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:53:52',
                'updated_at' => '2026-04-14 18:35:49',
            ],
            [
                'id' => 16,
                'user_id' => 3,
                'membership_id' => 1,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 300000.00,
                'pt_sessions_left' => 0,
                'status' => 'cancelled',
                'cancel_reason' => 'cút đi',
                'cancelled_at' => '2026-04-15 08:36:29',
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:56:45',
                'updated_at' => '2026-04-14 18:36:29',
            ],
            [
                'id' => 17,
                'user_id' => 3,
                'membership_id' => 1,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 300000.00,
                'pt_sessions_left' => 0,
                'status' => 'cancelled',
                'cancel_reason' => 'tôi ko muốn dky nx',
                'cancelled_at' => '2026-04-15 08:33:31',
                'frozen_until' => null,
                'created_at' => '2026-04-14 17:59:38',
                'updated_at' => '2026-04-14 18:33:31',
            ],
            [
                'id' => 20,
                'user_id' => 3,
                'membership_id' => 2,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 800000.00,
                'pt_sessions_left' => 4,
                'status' => 'cancelled',
                'cancel_reason' => 'tôi ko muốn dky th',
                'cancelled_at' => '2026-04-15 08:30:21',
                'frozen_until' => null,
                'created_at' => '2026-04-14 18:06:08',
                'updated_at' => '2026-04-14 18:30:21',
            ],
            [
                'id' => 23,
                'user_id' => 3,
                'membership_id' => 3,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 1500000.00,
                'pt_sessions_left' => 12,
                'status' => 'active',
                'cancel_reason' => null,
                'cancelled_at' => null,
                'frozen_until' => null,
                'created_at' => '2026-04-14 18:17:48',
                'updated_at' => '2026-04-14 18:18:05',
            ],
            [
                'id' => 24,
                'user_id' => 3,
                'membership_id' => 3,
                'trainer_id' => null,
                'start_date' => '2026-04-15',
                'end_date' => '2026-05-15',
                'final_price' => 1500000.00,
                'pt_sessions_left' => 12,
                'status' => 'cancelled',
                'cancel_reason' => 'ko mua',
                'cancelled_at' => '2026-04-22 00:35:08',
                'frozen_until' => null,
                'created_at' => '2026-04-14 18:56:06',
                'updated_at' => '2026-04-21 17:35:08',
            ]
        ]);
    }
}
