<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->delete();

        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'admin',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => '2026-04-02 16:29:21',
                'created_at' => '2026-04-02 15:34:25',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 2,
                'name' => 'Client Test',
                'email' => 'client@gmail.com',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'user',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => '2026-04-02 16:29:31',
                'created_at' => '2026-04-02 15:34:26',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 3,
                'name' => 'Đức Anh Nguyễn',
                'email' => 'anp93005@gmail.com',
                'password' => '$2y$10$h/Q.8WCBlsIRQMNDQkUXquGvs9f0.Rh0.YjRP00y9qlFX62hp3KP.',
                'role' => 'user',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => '/storage/avatars/UIbibMtXLrwdzJG9FUcXs4XL7FpZdB7YMVGSSwGm.jpg',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-02 15:38:04',
                'updated_at' => '2026-04-21 15:20:25',
            ],
            [
                'id' => 5,
                'name' => 'Nguyễn Minh Tuấn',
                'email' => 'tuan.gym@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'gym',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => '/storage/avatars/K7qM7QeoRcE9gfmP1lG3v07Vtyt8Zw5QeIe0eKBP.jpg',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-10 16:00:39',
                'updated_at' => '2026-04-23 02:23:37',
            ],
            [
                'id' => 6,
                'name' => 'Trần Thị Lan',
                'email' => 'lan.yoga@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'yoga',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=500&q=80&auto=format&fit=crop',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-10 16:00:40',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 7,
                'name' => 'Lê Văn Hùng',
                'email' => 'hung.boxing@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'gym',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?w=500&q=80&auto=format&fit=crop',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-10 16:00:40',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 8,
                'name' => 'Phạm Thu Hà',
                'email' => 'ha.fitness@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'both',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => '/storage/avatars/w6zVBxJQZFsSVaX9KerUAB7YKBzhpFtsVBVmKYEP.jpg',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-10 16:00:40',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 9,
                'name' => 'Phạm Thu Hà',
                'email' => 'thuha12@gmail.com',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'both',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-11 00:04:49',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 10,
                'name' => 'Phan Đức Tú',
                'email' => 'tubun2@gmail.com',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'staff',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-11 00:18:02',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 11,
                'name' => 'Admin User',
                'email' => 'admin@dummy.com',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'user',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-11 01:46:51',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 12,
                'name' => 'Lê Văn Hùng',
                'email' => 'hung.bodybuilding@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'gym',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?w=500&q=80&auto=format&fit=crop',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-15 20:42:41',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 13,
                'name' => 'Phạm Thu Hà',
                'email' => 'ha.yoga@extrafit.vn',
                'password' => '$2y$10$olk10lusqrfMu7nDf9.H0O9V8642pb2S/h.7jIb2LpRP81qCwdxSC',
                'role' => 'trainer',
                'specialization' => 'yoga',
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => 'https://images.unsplash.com/photo-1609899537878-49e9196c5bcd?w=500&q=80&auto=format&fit=crop',
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-15 20:42:41',
                'updated_at' => '2026-04-21 02:30:31',
            ],
            [
                'id' => 15,
                'name' => 'duc anh',
                'email' => 'chau12@gmail.com',
                'password' => '$2y$10$hR4UxDITp6yfPCZh/TNJ2uYG12NNQfDZXovN5FKfQVRNgnpE20Pr6',
                'role' => 'staff',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-21 15:51:23',
                'updated_at' => '2026-04-21 15:51:23',
            ],
            [
                'id' => 16,
                'name' => 'Cậy Nguyễn',
                'email' => 'nguyencay280668@gmail.com',
                'password' => '$2y$10$j7Eoc7spPk7FYlYNcw/cHOK7kR7EyholrxK0Ztny0d2jmsmaANi7u',
                'role' => 'user',
                'specialization' => null,
                'price_per_session' => 500000.00,
                'is_available' => 1,
                'avatar_url' => null,
                'is_active' => 1,
                'email_verified_at' => null,
                'created_at' => '2026-04-23 02:06:56',
                'updated_at' => '2026-04-23 02:06:56',
            ],
        ]);
    }
}
